"""Add interview timing fields to applications

Revision ID: 2025010301
Revises: 2025010201
Create Date: 2025-01-03 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025010301'
down_revision: Union[str, None] = '2025010201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('time_limit_minutes', sa.Integer(), server_default='120', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'time_limit_minutes')
    op.drop_column('applications', 'completed_at')
    op.drop_column('applications', 'started_at')
    # ### end Alembic commands ###
